/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms;

/**
 *
 * @author ABHI SHREE JAIN
 */
public class SMCnext extends javax.swing.JFrame {

    /**
     * Creates new form SMCnext
     */
    public SMCnext() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addsmc = new javax.swing.JButton();
        addstud = new javax.swing.JButton();
        delstud = new javax.swing.JButton();
        view_orders = new javax.swing.JButton();
        view_new = new javax.swing.JButton();
        view_read = new javax.swing.JButton();
        view_rep = new javax.swing.JButton();
        delsmc = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1178, 755));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1178, 755));
        jPanel1.setLayout(null);

        addsmc.setFont(new java.awt.Font("Gotham Black", 0, 18)); // NOI18N
        addsmc.setText("Add SMC member");
        addsmc.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(addsmc);
        addsmc.setBounds(263, 96, 230, 40);

        addstud.setFont(new java.awt.Font("Gotham Black", 0, 18)); // NOI18N
        addstud.setText("Add student");
        addstud.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(addstud);
        addstud.setBounds(263, 198, 230, 40);

        delstud.setFont(new java.awt.Font("Gotham Black", 0, 18)); // NOI18N
        delstud.setText("Delete student");
        delstud.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(delstud);
        delstud.setBounds(643, 201, 230, 40);

        view_orders.setFont(new java.awt.Font("Gotham Black", 0, 18)); // NOI18N
        view_orders.setText("View orders");
        view_orders.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(view_orders);
        view_orders.setBounds(260, 310, 230, 40);

        view_new.setFont(new java.awt.Font("Gotham Black", 0, 18)); // NOI18N
        view_new.setText("View new complaints");
        view_new.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(view_new);
        view_new.setBounds(640, 310, 230, 40);

        view_read.setFont(new java.awt.Font("Gotham Black", 0, 18)); // NOI18N
        view_read.setText("View read complaints");
        view_read.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(view_read);
        view_read.setBounds(260, 430, 230, 40);

        view_rep.setFont(new java.awt.Font("Gotham Black", 0, 18)); // NOI18N
        view_rep.setText("View replies");
        view_rep.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(view_rep);
        view_rep.setBounds(650, 430, 230, 40);

        delsmc.setFont(new java.awt.Font("Gotham Black", 0, 18)); // NOI18N
        delsmc.setText("Delete SMC member");
        delsmc.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(delsmc);
        delsmc.setBounds(643, 96, 230, 40);

        jButton1.setFont(new java.awt.Font("Gotham Black", 0, 18)); // NOI18N
        jButton1.setText("GO BACK");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(460, 550, 230, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ABHI SHREE JAIN\\Pictures\\Saved Pictures\\steamed-fish-5w_use.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1180, 710);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SMChome obj=new SMChome();
        obj.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SMCnext.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SMCnext.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SMCnext.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SMCnext.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SMCnext().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addsmc;
    private javax.swing.JButton addstud;
    private javax.swing.JButton delsmc;
    private javax.swing.JButton delstud;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton view_new;
    private javax.swing.JButton view_orders;
    private javax.swing.JButton view_read;
    private javax.swing.JButton view_rep;
    // End of variables declaration//GEN-END:variables
}
